### PR TITLE
Added fix from issue #3 and made test

### LINKED ISSUE #3: List concat serializes the objects in the list before adding it to the resulting list ~5
From: 

 - https://github.com/canjs/canjs/issues/1616

```
sourceList[ 0 ] !== ( sourceList.concat( [] ) )[ 0 ];
```

This should be fixed in `can-define/list/list`.

### PR DESCRIPTION
**Pull request by Sinjhin**
Closes #3 

Please review changed line https://github.com/canjs/can-list/blob/3-concat-deep-equals/can-list_test.js#L164 Based on discussion https://github.com/canjs/canjs/issues/1616#issuecomment-141188626 to make sure this is what we want.

Concatenating a map will to the list will no longer serialize that map.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Yeah, the change to the test is wrong.  We should mimic the behavior of how arrays work:

```
var l = ['a','b','c'];
var c = l.concat([2,1], [0]);
c //-> ["a", "b", "c", 2, 1, 0]
```

This means that if a List is an argument, its non-serialized items should be concat-ed.

File: can-list.js [hunk 1]
```diff
@@ -765,12 +764,73 @@ assign(List.prototype, {
...
+	// },
+
+	concat: function() {
+
+		var args = [],
+			MapType = this.constructor.Map,
+			// Function that serializes the passed arg if
+			// type does not match MapType of `this` list
+			// then adds to args array
+			serializeNonTypes = function(arg) {
```
Comment (justinbmeyer) [inline can-list.js]: best not to regenerate these sorts of things every call to concat.

File: can-list_test.js [hunk 2]
```diff
@@ -172,13 +174,49 @@ test('Array accessor methods', 11, function () {
...
+		{ foo: "Bar" }
+	]);
+
+	ok(l[0] === concatenated[0], "They are Equal");
+	ok(l[1] === concatenated[1], "They are Equal");
+
+});
+
+test('Lists with maps concatenate properly', function() {
+	Person = Map.extend();
```
Comment (justinbmeyer) [inline can-list_test.js]: make sure you use `var`

File: can-list.js [hunk 3]
```diff
@@ -205,6 +205,16 @@ var List = Map.extend(
 		serialize: function () {
 			return mapHelpers.serialize(this, 'serialize', []);
 		},
+		// Function that serializes the passed arg if
+		// type does not match MapType of `this` list
+		// then adds to args array
+		serializeNonTypes: function(MapType, arg, args) {
```
Comment (justinbmeyer) [inline can-list.js]: We shouldn't add unnecessary things to the prototype.  Please make this a function in the surrounding scope.
